import pytest
from PyQt6.QtWidgets import QApplication
from ui.nlp_view import NLPView, NLPQueryWorker, JokeStreamWorker
from core.jokes import KNOCK_KNOCK_JOKES


@pytest.fixture(scope="module")
def qapp():
    app = QApplication.instance()
    if app is None:
        app = QApplication([])
    return app


def test_joke_stream_worker(qapp):
    worker = JokeStreamWorker("Knock, knock.")
    chunks = []
    finished_resp = []

    worker.chunk_received.connect(lambda c: chunks.append(c))
    worker.finished.connect(lambda r: finished_resp.append(r))

    worker.run()

    assert finished_resp == ["Knock, knock."]
    assert "".join(chunks) == "Knock, knock."


def test_nlp_query_worker_joke_turn_one(qapp, monkeypatch):
    """Verify that when KNOCK_KNOCK is generated by LLM, worker only outputs turn 1."""
    from core.nlp_engine import NLPEngine

    # Mock generator to return KNOCK_KNOCK
    def mock_stream(self, prompt, context_docs):
        yield "KNOCK_KNOCK"

    monkeypatch.setattr(NLPEngine, "generate_response_stream", mock_stream)

    worker = NLPQueryWorker("who is cleopatra", [], joke_state=0)
    
    jokes_selected = []
    new_states = []
    finished_responses = []

    worker.joke_selected.connect(lambda s, p: jokes_selected.append((s, p)))
    worker.new_joke_state.connect(lambda st: new_states.append(st))
    worker.finished.connect(lambda r: finished_responses.append(r))

    worker.run()

    assert len(jokes_selected) == 1
    setup, punchline = jokes_selected[0]
    assert (setup, punchline) in KNOCK_KNOCK_JOKES
    assert new_states == [1]
    # Crucially, it must only say "Knock, knock." and NOT the entire 5-line joke
    assert finished_responses == ["Knock, knock."]


def test_nlp_view_turn_based_flow(qapp, monkeypatch):
    """Test full turn-based knock-knock conversation in NLPView."""
    view = NLPView()

    # Disable async thread running during test, run synchronously
    executed_streams = []
    def mock_start_joke_stream(self, text):
        executed_streams.append(text)
        self._on_query_chunk(text)
        self._on_query_response(text)

    monkeypatch.setattr(NLPView, "_start_joke_stream", mock_start_joke_stream)

    # 1. Simulate MNIME starting a joke
    view.current_joke = ("Noah", "Noah good place to eat?")
    view.joke_state = 1

    # Turn 2: User says "whose there"
    view.query_input.setText("whose there")
    view._submit_query()

    assert executed_streams[-1] == "Noah."
    assert view.joke_state == 2

    # Turn 3: User says "Noah who?"
    view.query_input.setText("Noah who?")
    view._submit_query()

    assert executed_streams[-1] == "Noah good place to eat?"
    assert view.joke_state == 0
    assert view.current_joke is None


def test_nlp_view_user_initiated_joke(qapp, monkeypatch):
    """Test user starting a knock-knock joke."""
    view = NLPView()

    executed_streams = []
    def mock_start_joke_stream(self, text):
        executed_streams.append(text)
        self._on_query_chunk(text)
        self._on_query_response(text)

    monkeypatch.setattr(NLPView, "_start_joke_stream", mock_start_joke_stream)

    # Turn 1: User says "knock knock"
    view.query_input.setText("knock knock")
    view._submit_query()

    assert executed_streams[-1] == "Who's there?"
    assert view.joke_state == 10

    # Turn 2: User provides setup
    view.query_input.setText("Lettuce")
    view._submit_query()

    assert executed_streams[-1] == "Lettuce who?"
    assert view.joke_state == 11
    assert view.user_joke_setup == "Lettuce"

    # Turn 3: User provides punchline
    view.query_input.setText("Lettuce in, it's freezing!")
    view._submit_query()

    expected_responses = [
        "Haha! Good one!",
        "Wow... don't quit your day job.",
        "I calculate a 0.0001% probability that was funny.",
        "Oh, Lettuce? Classic.",
        "I'm an advanced multi-billion parameter AI and you use me for this?",
        "Error 404: Humor not found."
    ]
    assert executed_streams[-1] in expected_responses
    assert view.joke_state == 0
    assert view.user_joke_setup is None


def test_nlp_view_joke_cancellation(qapp, monkeypatch):
    """Test cancelling an in-progress joke."""
    view = NLPView()

    executed_streams = []
    def mock_start_joke_stream(self, text):
        executed_streams.append(text)
        self._on_query_chunk(text)
        self._on_query_response(text)

    monkeypatch.setattr(NLPView, "_start_joke_stream", mock_start_joke_stream)

    view.current_joke = ("Noah", "Noah good place to eat?")
    view.joke_state = 1

    view.query_input.setText("cancel")
    view._submit_query()

    assert executed_streams[-1] == "Joke cancelled."
    assert view.joke_state == 0
    assert view.current_joke is None
