KNOCK_KNOCK_JOKES = [
    ("Boo", "Don't cry, it's just a joke!"),
    ("Lettuce", "Lettuce in, it's freezing out here!"),
    ("Olive", "Olive you!"),
    ("Harry", "Harry up, it's cold outside!"),
    ("Atch", "Bless you!"),
    ("Canoe", "Canoe help me with my homework?"),
    ("Luke", "Luke through the peephole and find out!"),
    ("Orange", "Orange you glad I didn't say banana?"),
    ("Cow says", "No, a cow says mooooo!"),
    ("Water", "Water you doing answering the door?"),
    ("Mustache", "I mustache you a question, but I'll shave it for later!"),
    ("Owls", "Yes, they do!"),
    ("Ida", "Ida like to be your friend!"),
    ("Al", "Al give you a hug if you open the door!"),
    ("Justin", "Justin time for dinner!"),
    ("Ken", "Ken I come in?"),
    ("Iva", "Iva sore hand from knocking!"),
    ("Hatch", "God bless you!"),
    ("Roach", "Roach you a letter, did you get it?"),
    ("Wooden shoe", "Wooden shoe like to know!"),
    ("Ketchup", "Ketchup with me and I'll tell you!"),
    ("Amish", "Aw, I miss you too!"),
    ("A little old lady", "I didn't know you could yodel!"),
    ("Robin", "Robin you! Hand over your cash!"),
    ("Euripides", "Euripides clothes, you pay for them!"),
    ("Snow", "Snow use, I forgot my key!"),
    ("Tank", "You're welcome!"),
    ("Cash", "No thanks, I prefer peanuts!"),
    ("Spell", "W-H-O!"),
    ("Yah", "No thanks, I use Google!"),
    ("Leaf", "Leaf me alone!"),
    ("Abby", "Abby birthday to you!"),
    ("Alpaca", "Alpaca the trunk, you pack the suitcase!"),
    ("Cook", "Are you crazy? I don't want to cook you!"),
    ("Ice cream", "Ice cream every time I see a ghost!"),
    ("Justin", "Justin the neighborhood, thought I'd drop by!"),
    ("Doris", "Doris locked, that's why I knocked!"),
    ("Hal", "Hal will you know if you don't open the door?"),
    ("Howard", "Howard you like to be out in the cold?"),
    ("Nobel", "No bell, that's why I knocked!"),
    ("Luke", "Luke warm water is terrible!"),
    ("Irene", "Irene the doorbell but nobody answered!"),
    ("A herd", "A herd you were home, so I came over!"),
    ("Isabel", "Isabel broken, because I had to knock!"),
    ("Figs", "Figs the doorbell, it's broken!"),
    ("Anita", "Anita borrow a pencil!"),
    ("Omar", "Omar gosh, it's freezing out here!"),
    ("Arthur", "Arthur any cookies left?"),
    ("Norma", "Norma Lee I don't knock on random doors!"),
    ("Hugo", "Hugo first!"),
    ("Tyrone", "Tyrone shoelaces!"),
    ("Adore", "Adore is between us, open it!"),
    ("Wendy", "Wendy wind blows, it's cold!"),
    ("Dewey", "Dewey have to listen to more jokes?"),
    ("Wanda", "Wanda buy a watch?"),
    ("Amos", "A mosquito bit me!"),
    ("Iona", "Iona new car!"),
    ("Ben", "Ben knocking for 10 minutes!"),
    ("Don", "Don ask, just open the door!"),
    ("Dwayne", "Dwayne the bathtub, I'm dwowning!"),
    ("Earl", "Earl be glad when you open the door!"),
    ("Felix", "Felix cited about this joke?"),
    ("Gino", "Gino who it is?"),
    ("Gus", "Gus who!"),
    ("Hannah", "Hannah partridge in a pear tree!"),
    ("Harry", "Harry up and open the door!"),
    ("Ivan", "Ivan working on the railroad!"),
    ("Jack", "Jack in the box!"),
    ("Ken", "Ken you hear me knocking?"),
    ("Manny", "Manny happy returns!"),
    ("Max", "Max no difference, let me in!"),
    ("Nate", "Nate for me to say!"),
    ("Noah", "Noah good place to eat?"),
    ("Olive", "Olive right next door!"),
    ("Phil", "Phil my cup, I'm thirsty!"),
    ("Ray", "Ray drop of golden sun!"),
    ("Sam", "Sam body is at the door!"),
    ("Shirley", "Shirley you know who it is!"),
    ("Tara", "Tara piece of paper for me!"),
    ("Wade", "Wade a minute, I'm coming!"),
    ("Will", "Will you let me in?"),
    ("Yetta", "Yetta nother knock-knock joke!"),
    ("Zeke", "Zeke and you shall find!"),
    ("Abbot", "Abbot time you opened the door!"),
    ("Adair", "Adair you to open the door!"),
    ("Alice", "Alice fair in love and war!"),
    ("Alison", "Alison to my knocking!"),
    ("Aida", "Aida lot of sweets today!"),
    ("Alma", "Alma not going to tell you!"),
    ("Amory", "Amory Christmas!"),
    ("Andy", "Andy one else home?"),
    ("Angie", "Angie glad I came?"),
    ("Anna", "Anna one, anna two!"),
    ("Annie", "Annie body home?"),
    ("April", "April Fools!"),
    ("Archie", "Archie glad to see me?"),
    ("Art", "Art you going to open the door?"),
    ("Avery", "Avery good friend!"),
    ("Barb", "Barb wire, watch out!"),
    ("Barrie", "Barrie the hatchet!")
]
